#!/bin/bash
echo Java OpenCV Hello World Script
export JAVA_HELLOWORLD_ARCH=x86_64
export JAVA_HELLOWORLD_OPENCV_VERSION=opencv-2413
export JAVA_HELLOWORLD_REL_PATH_JAR=$JAVA_HELLOWORLD_ARCH/jar/$JAVA_HELLOWORLD_OPENCV_VERSION.jar
export JAVA_HELLOWORLD_REL_PATH_SO=$JAVA_HELLOWORLD_ARCH/so/

javac -cp $JAVA_HELLOWORLD_REL_PATH_JAR HelloWorld.java
java -Djava.library.path=$JAVA_HELLOWORLD_REL_PATH_SO -cp .:$JAVA_HELLOWORLD_REL_PATH_JAR HelloWorld
